# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: car-racing-service
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: car-racing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
